# Generated by Django 4.2.5 on 2023-10-20 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profilemodel_avatar_profilemodel_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='profile',
            new_name='avatar',
        ),
    ]
