# Generated by Django 4.2.5 on 2023-10-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=25)),
                ('year', models.IntegerField()),
                ('seats', models.IntegerField(default=5)),
                ('type', models.CharField(max_length=25)),
                ('engine_v', models.FloatField()),
            ],
            options={
                'db_table': 'cars',
            },
        ),
    ]
