# Generated by Django 4.2.5 on 2023-10-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='seats',
            field=models.IntegerField(),
        ),
    ]
