# Generated by Django 4.2.5 on 2023-10-05 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carmodel_updated_at_alter_carmodel_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 10, 5, 17, 52, 37, 912380)),
            preserve_default=False,
        ),
    ]
