# Generated by Django 4.2.5 on 2023-10-20 17:45

import core.services.common.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_carmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to=core.services.common.services.upload_car_image),
        ),
    ]
