# Generated by Django 4.2.5 on 2023-10-20 11:03

import core.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profilemodel_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='avatar',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='profile',
            field=models.ImageField(blank=True, upload_to=core.services.services.upload_avatar),
        ),
    ]
